name: dusa
description: Dusa package  is an SDK that connects your Dart and Flutter applications to Dusa - a decentralized exchange (DEX) built on the Massa blockchain.
version: 1.0.7
repository: https://github.com/nafsilabs/dusa-dart
homepage: https://www.nafsi.world

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  massa: ^1.9.6

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
